### ISSUE TITLE
Creating Editor simple example

### ISSUE THREAD

**Issue by Askiater** [lochbrunner/react-flow-editor#86]
Hi guys! You library looks very promising and i try to use it in my current react project. But i'm facing a problem.
Try to reproduce your basic example to creating a simple react component like this one:
![image](https://user-images.githubusercontent.com/31743222/130635772-a6b16ef1-c56c-4eaf-a9fe-9d95b4c5a5ca.png)
To achieve that download latest npm package: 0.4.3
And after i implement that component and normally just create bundle via webpack (a lot additional react-based libraries already connected to project and they work fine) when i'm trying to serve it i getting an error:
![image](https://user-images.githubusercontent.com/31743222/130633889-3b6e3978-7aba-4265-8cfc-39dfc783e08a.png)
If we gonna try to inspect it it is located to a Editor component.
![image](https://user-images.githubusercontent.com/31743222/130634123-7e23986c-6bd2-4f8e-a17e-0d55dc9cb94f.png)

Did i miss something?

Environment:
 - OS: Windows 10, x64
 - Browser: Chrome 
 - npm v6.14.14
 - node v14.17.5
 - react-flow-editor v0.4.3
 - package.json
 `"devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "babel-loader": "^8.1.0",
    "file-loader": "^6.1.1",
    "html-loader": "^1.3.2",
    "html-webpack-plugin": "^4.5.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-flow-editor": "^0.4.3",
    "react-svg-loader": "^3.0.3",
    "webpack": "^5.10.0",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
  },`

**Comment by lochbrunner** [comment]
Hi @Askiater thanks for that report. It seems that `setImmediate` is not supported by modern browsers anymore.
However, we could replace is by `setTimeout`.

**Comment by lochbrunner** [comment]
@Askiater does it work with the latest version `0.6.1` ?

**Comment by Askiater** [comment]
![image](https://user-images.githubusercontent.com/31743222/130681413-1a4e0608-38ff-4b3c-8a63-9355461833e0.png)
They render in kinda weird position, but know it working! Thanks
